list = ["Soviet Russia", "Soviet Russia", "Soviet Russia", "Soviet Russia", "Soviet Russia",
  "a USB cable", "a small boulder", "a pointed stick", "a shotgun", "dust",
  "AOL CDs", "peanut butter", "a golf club", "air", "water", "a stapler",
  "a pair of scissors", "a size 13 bowling shoe", "a dead mouse", "a toilet",
  "a shampoo bottle", "Howard Dean", "the State of Maryland", "a piano",
  "Sparkling Cider", "a box of Kleenexes", "a Fig Newton", "an Apple ][",
  "a gallon of milk", "a Cuban cigar", "a 1968 Corvette", "a chess set",
  "a ZIP disk", "a can of Pig Brains with Gravy", "a trumpet", "a $2 bill",
  "the 2006 US Federal Tax Code", "Charles Manson's hair clippings", "yes",
  "CSI Season 1 DVD Set", "a pair of scissors", "nothing in particular",
  "99 bottles of beer on the wall", "a beanstalk", "a long pole", "lint",
  "a Patriot Missile", "an Oak 2x4", "a ROKR cellphone", "a light bulb",
  "a smoothbore depleted uranium sniper shell", "lots and lots of penguins",
  "a bottle of Welch's Sparkling White Grape Juice Cocktail (non-alcoholic)",
  "a trumpet mouthpiece", "a pair of headphones", "three sporks", "stuff",
  "a spiral fluorescent light bulb", "Sony's DRM Software", "Deep Space 9",
  "a slice of pizza", "a nosehair plucker", "three grains of sand", "earwax",
  "'One Fish Two Fish Red Fish Blue Fish'", "a coconut monkey", "a bathtub",
  "a Lego head, one of those cool ones with the sunglasses and stubble",
  "The Artist Formerly known as The Artist Formerly known as Prince", "ants",
  "bellybutton lint", "the 1932 World's Fair", "a Sharpie, Ultra Fine Point",
  "15 golf ball tees", "a roll of pennies", "a Chinese Crested Hairless dog",
  "dental floss", "a toothpick", "a cow pie", "a toilet seat cover", "Jewel",
  "a toilet seat", "12 pounds of bacon", "a shrimp, a starfish, and a pigmy",
  "a fur coat", "a dot matrix printer", "a leg lamp", "RITZ bits", "a sock",
  "a mechanical pencil (0.5mm lead)", "fuzzy dice", "a watch", "a keyboard",
  "toenail clippings", "the letter 'L'", "8 dill pickles", "carpet remnants",
  "one of those squishy rubbery things that spring keyboard keys back up",
  "an EIDE cable", "a tube of m&m's minis", "a gerbil dressed as Domo-kun",
  "two suction cups, a peanut, and a can of cooking spray", "an ice skate",
  "a slinkey", "3 hard boiled eggs", "french vanilla icecream", "a salad",
  "5 poker decks", "a stapler", "some 6 year old's two front teeth",
  "pickled pigs feet", "a trap door spider", "a stained glass window",
  "a bell tower", "string, wax, a bowling ball, and a tape measurer", "Twix",
  "a shoebox", "an ABIT motherboard", "a large yacht", "an LCD screen",
  "plains, trains, and automobiles", "a campfire", "peanut butter and syrup",
  "melted chocolate", "a crowbar", "Emperor Palpatine", "a sheet of drywall",
  "a ceiling fan blade", "a broken tennis racquet", "2 pair of water skis",
  "a 38 inch tire", "a smoke alarm", "a plastic fly", "a Pepsi cap",
  "a gopher", "a gopher trap", "a random kitchen utensil", "a plutonium rod",
  "peach fuzz", "oyster crackers", "electrolytes", "kosher salt", "termites",
  "dihydrogen monoxide", "a partial solar eclipse", "crayons", "an anteater",
  "a plastic hanger, tube kind, not the ones that come with items from a store",
  "the kitchen sink", "a refrigerator", "a broken shot glass", "curly fries",
  "73 cranberries", "David Hasselhoff", "a can of tomato sauce", "a pimple",
  "bamboo stilts", "a Tickle Me Elmo", "a Mickey Mouse Clock", "soy milk",
  "a Capria Sun pouch", "a rusty shot put ball", "Ernest Hemingway",
  "a random sea slug", "Gigli (Special Edition DVD)", "tofu casserole",
  "a spider, 4 toenail clippings, and a toupee", "24 pancakes", "Dr. Phill",
  "chicken parmesan, an innertube, and dental floss", "used chewing gum",
  "termites, packing peanuts, and 14 gummy bears", "used corn husks",
  "a hockey stick", "nine hockey pucks", "a bag of dogfood", "738 buttons",
  "Montel", "18 cans of Alpo", "random emoticons", "a newspaper from 1947",
  "a random tv show, but not a 'random' show as in 'OMG that was random' but a random show as in, well, random throw of the dice",
  "a random tv show", "a picknick table", "a ping pong table", "a techno DJ",
  "a lobster, three onions, seven pencils, and a chewed up roll of 'Fruit by the Foot'",
  "chicken legs", "two pitchforks", "Nebraska", "a .torrent of Darkwing Duck",
  "America's Next Top Model", "a 52 inch plasma monitor",
  "a fax machine", "four tennis racquets tied together to form a pyramid",
  "3 coupons and 2 AAA batteries", "a clown shoe", "a POS graphics card",
  "random prescription medicine", "three muffins and two slices of toast",
  "dental floss", "42 Pringles cans", "flakes of dead skin", "a shoe",
  "2 plastic coat hangers and a roll of nickles", "38 IDE cables", "an ant",
  "a box of t-shirts, 3 yards of dental floss, and a broken plastic fork",
  "the remains of Humpty Dumpty after all the King's Men couldn't put him back together",
  "7 egg whites and a cup of flower", "38 pigs and their farmer Willifred",
  "a first aid kit", "Salad Shooter(tm)", "a 17 car pile up on the freeway",
  "200 yards of barbed wire", "a PEZ dispenser filled with Tic-Tacs", "lice",
  "a Universal Power Supply backup battery", "a 4U racmount server",
  "314 empty envelops with prepaid postage from Credit Card companies",
  "mizspeld werds", "13 pounds of dust", "a spider's web", "a table leg",
  "42 Oreo Cookies, 2 Watermelons, 4 machine guns, and twisty ties",
  "a NERF bow and arrow", "an empty can of wasp spray", "the summer sky",
  "bubble wrap that has been painted blue", "99 red ballons", "bubbles",
  "the interwebs", "miscellaneous body fluids", "21,357 DVDs", "the letter W",
  "a broken watch that has been dipped in gasoline", "7 potted plants",
  "shoes, a rock, toilet paper, 3 inch plastic dice, and a Swiss Army knife with the main blade removed",
  "32 freshly beheaded chickens", "a New Kids on the Block tape", "a Furby",
  "fiiiiiiiiiiiive goooolden riiiiiiiiings", "Hobart, Tasmania", "Nunavut",
  "James Brown", "Danny DeVito", "Keanu Reeves", "Rosie O'Donnell", "a belt",
  "Ashton Kutcher", "the passenger mirror of a 1972 Mercedes-Benz 280SEL",
  "3 rose bushes", "a box of 248 crayons that are half used", "a cold",
  "2 bottles of 'all small & mighty' with stainlifter and 3x concentrated laundry detergent",
  "a bicycle helmet", "Cardcaptor Sakura", "a spider plant", "mayonnaise",
  "George, the bellboy from Manhattan", "Wooster", "Jeeves", "an oven mit",
  "a brown paper bag filled with Cheetos", "a Swingline 790 stapler",
  "a Linksys 16-Port Workgroup Switch", "200 yards of Cat 4 cable", "Nemo",
  "a smoke detector", "moldy cheese that a mouse didn't eat", "33 broken CDs",
  "Swiss Miss powdered Hot Chocolate with little marshmallows", "a spatula",
  "a Five Star binder", "a spider's egg sack", "3 dozen no bake cookies",
  "a glass of water", "5 pounds of asphault", "a salamander", "yellow polk-a-dotted mushrooms",
  "a wedding invitation", "dangly earrings", "empty and crumpled popcans"]